### ISSUE TITLE
Bug in GsonMessageBodyProvider, using getField instead of getDeclaredField

### ISSUE THREAD

**Issue by dgrant** [immutables/immutables#509]
This doesn't work with getField because the fields it's trying to access are private. This causes serializeNulls setting in the Gson object to not take effect.

```
    private static boolean accessField(Gson gson, String name, boolean defaultValue) {
      try {
        Field field = Gson.class.getField(name);
        field.setAccessible(true);
        return field.get(gson) == Boolean.TRUE;
      } catch (Exception ex) {
        return defaultValue;
      }
    }
```

Are you guys able to make this quick fix and push a minor version out? I'd create a fork and PR but that seems unnecessary for this minor change.

**Comment by dgrant** [comment]
Actually I think field.get(gson) == Boolean.TRUE is buggy too. Should be Boolean.TRUE.equals(field.get(gson)). Stepping through with a debugger confirms that. Need some unit tests for this. I can try to do this but no promises. I've fixed our issues with serializeNulls by asking our frontend developer to handle missing keys in the map, as opposed to explicit nulls.

**Comment by elucash** [comment]
while upgrading to Gson 2.8.0: `serializeNulls`  and `htmlSafe` are now exposed on the `Gson`, but `prettyPrint` is still not, so to get it reflectively the fix still applies

**Comment by elucash** [comment]
released in 2.4.0, thank you!

**Comment by dgrant** [comment]
thank you!
